version: '3'
services:

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: backend

  # tests:
  #   build: ./tests
  #   container_name: tests
  #   depends_on:
  #     backend:
  #       condition: service_started