version: '3'
services:

  backend:
    build: ./backend
    ports:
      - "5000:5000"

  tests:
    build: ./tests
    image: api_tests
    depends_on:
      backend:
        condition: service_started