version: 2.1
jobs:
  run-tests:
    machine: 
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: "Backend"
          command: |
            docker build -t backend ./backend
            docker run -d  -p 5000:5000 backend
      - run:
          name: "Run Tests"
          command: |
            cd tests
            npm install playwright
            npm install ajv
            npm install nock
            npx playwright test

workflows:
  run-tests-workflow:
    jobs:
      - run-tests